/*******************************************************************************
   Drop database if it exists
********************************************************************************/
set global SQL_MODE="NO_ENGINE_SUBSTITUTION";


DROP DATABASE IF EXISTS `CONTROL_ACCESO`;
/*******************************************************************************
   Create database
********************************************************************************/
CREATE DATABASE `CONTROL_ACCESO`;
USE `CONTROL_ACCESO`;
SET default_storage_engine = `InnoDB`;
-- -----------------------------------------------------
-- Table `NIVEL_DE_ACCESO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NIVEL_DE_ACCESO` (
	`ID_NIVEL_DE_ACCESO` INT NOT NULL,
	`NOMBRE_HABITACION` VARCHAR(45) NULL,
	`NIVEL_DE_ACCESO` INT NULL,
	CONSTRAINT `PK_NIVEL_DE_ACCESO` PRIMARY KEY (`ID_NIVEL_DE_ACCESO`)
	);

-- -----------------------------------------------------
-- Table `NIVEL_DE_ACCESO_PERSONA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NIVEL_DE_ACCESO_PERSONA` (
	`ID_NIVEL_DE_ACCESO_PERSONA` INT NOT NULL,
	`ID_PERSONA` INT NOT NULL,
	`ID_NIVEL_DE_ACCESO` INT NOT NULL,
	`NIVEL_DE_ACCESO` INT NOT NULL ,
	`TAG_ID` INT  NOT NULL,
	CONSTRAINT `PK_NIVEL_DE_ACCESO_PERSONA` PRIMARY KEY (`ID_NIVEL_DE_ACCESO_PERSONA`)
	);
-- -----------------------------------------------------
-- Table `WORKPLACE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WORKPLACE` (
	`IDWORKPLACE` INT NOT NULL,
	`DIRECCION` VARCHAR(45),
	`NRO_OFICINA` INT ,
	 CONSTRAINT `PK_WORKPLACE` PRIMARY KEY (`IDWORKPLACE`)
  	);

-- -----------------------------------------------------
-- Table `PERSONA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PERSONA` (
	`IDPERSONA` INT  NOT NULL,
	`NIVEL_DE_ACCESO_P` INT  NOT NULL,
	`NOMBRE` VARCHAR(45) ,
	`ESTADO` VARCHAR(45),
	`IDWORKPLACE` INT  NOT NULL,

	 CONSTRAINT `PK_PERSONA`PRIMARY KEY (`IDPERSONA`)
	 );
-- -----------------------------------------------------
-- Table `HORARIO-LABORAL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HORARIO_LABORAL` (
	`HORA_ENTRADA` INT NULL,
	`HORARIO-SALIDA` INT NULL,
	`IDWORKPLACE` INT NOT NULL
	);


-- -----------------------------------------------------
-- Table `ESTADISTICA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ESTADISTICA` (
	`ID_ESTADISTICA` INT NOT NULL,
	`TAG ID` INT NULL,
	`HORA` INT NULL,
	`DIA` INT NULL,
	`PERMITIDO/DENEGADO` TINYINT NULL,
	`ENTRADA/SALIDA` TINYINT NULL,
	`ESTADISTICA` TINYINT NULL,
	CONSTRAINT `PK_ESTADISTICA` PRIMARY KEY (`ID_ESTADISTICA`)
	);
-- -----------------------------------------------------
-- Table `PUERTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PUERTA` (
  `ID_PUERTA` INT NOT NULL,
  `ABIERTA/CERRADA` TINYINT NULL,
  `ID_NIVEL_DE_ACCESO` INT NOT NULL,
  `ID_ESTADISTICA` INT NOT NULL,
  `IDWORKPLACE` INT NOT NULL,
  CONSTRAINT `PK_PUERTA` PRIMARY KEY (`ID_PUERTA`)
  );
-- -----------------------------------------------------
-- CREATE INDEX
-- -----------------------------------------------------
CREATE INDEX `IFK_IDWORKPLACE`        ON `WORKPLACE` 	( `IDWORKPLACE`);
CREATE INDEX `IFK_ID_NIVEL_DE_ACCESO` ON `NIVEL_DE_ACCESO`   ( `ID_NIVEL_DE_ACCESO`);
CREATE INDEX `IFK_ID_NIVEL_DE_ACCESO_PERSONA` ON `NIVEL_DE_ACCESO_PERSONA`   ( `ID_NIVEL_DE_ACCESO_PERSONA`);
CREATE INDEX `IFK_PUERTA_ESTADISTICA` ON `ESTADISTICA` 	( `ID_ESTADISTICA`) ;


ALTER TABLE `PERSONA` ADD CONSTRAINT `FK_WORKPLACE`
	FOREIGN KEY (`IDWORKPLACE`) REFERENCES `WORKPLACE` (`IDWORKPLACE`) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE `PERSONA` ADD CONSTRAINT `FK_NIVEL_DE_ACCESO_PERSONA`
FOREIGN KEY (`NIVEL_DE_ACCESO_P`) REFERENCES `NIVEL_DE_ACCESO_PERSONA` (`NIVEL_DE_ACCESO`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `HORARIO_LABORAL` ADD CONSTRAINT `FK_HORARIO_LABORAL`
	FOREIGN KEY (`IDWORKPLACE`) REFERENCES `WORKPLACE` (`IDWORKPLACE`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `PUERTA` ADD CONSTRAINT `FK_ID_NIVEL_DE_ACCESO`
	FOREIGN KEY (`ID_NIVEL_DE_ACCESO`) REFERENCES `NIVEL_DE_ACCESO` (`ID_NIVEL_DE_ACCESO`) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE `PUERTA` ADD CONSTRAINT `FK_ID_ESTADISTICA`
	FOREIGN KEY (ID_ESTADISTICA) REFERENCES `ESTADISTICA` (`ID_ESTADISTICA`) ON DELETE NO ACTION  ON UPDATE NO ACTION;
ALTER TABLE `PUERTA` ADD CONSTRAINT `FK_IDWORKPLACE`
	FOREIGN KEY (IDWORKPLACE) REFERENCES `WORKPLACE` (`IDWORKPLACE`) ON DELETE NO ACTION  ON UPDATE NO ACTION;
